version: '3.9'
services:
  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: elasticsearch_exporter
    network_mode: host
    command:
      - '--es.uri=https://ELASTICSEARCH_ADMIN_USERNAME:ELASTICSEARCH_ADMIN_PASSWORD@127.0.0.1:9200'
      - '--es.all'
      - '--es.indices'
      - '--es.indices_settings'
      - '--es.cluster_settings'
      - '--es.snapshots'
      - '--es.shards'
      - '--es.ssl-skip-verify'
    restart: always
    ports:
    - "9114:9114"