---

# Installs elasticsearch_exporter running with docker-compose at Elasticsearch servers.
# Steps to install:
#     1. Set environment variables ELASTICSEARCH_ADMIN_USERNAME and ELASTICSEARCH_ADMIN_PASSWORD with proper credentials
#     2. Make sure that target server is in ansible_playbook/inventories/<inventory>/inventory file
#     3. Run ansible-playbook -i inventories/dev/inventory.dev -u <user> master.yml -l <group> -K

- name: Set variables
  tags: elasticsearch-exporter
  set_fact:
    es_username: "{{ lookup('env', 'ELASTICSEARCH_ADMIN_USERNAME') }}"
    es_password: "{{ lookup('env', 'ELASTICSEARCH_ADMIN_PASSWORD') }}"
    dc_file: /tmp/elasticsearch-exporter.yml

- name: Copy docker-compose file
  tags: elasticsearch-exporter
  ansible.builtin.copy:
    src: elasticsearch-exporter.yml
    dest: "{{ dc_file }}"
    force: true

- name: Replace credentials
  tags: elasticsearch-exporter
  ansible.builtin.replace:
    path: "{{ dc_file }}"
    regexp: "{{ item.template }}"
    replace: "{{ item.target }}"
  loop:
    - { template: "ELASTICSEARCH_ADMIN_USERNAME", target: "{{ es_username }}" }
    - { template: "ELASTICSEARCH_ADMIN_PASSWORD", target: "{{ es_password }}" }

- name: Run elastisearch exporter
  tags: elasticsearch-exporter
  command: "docker-compose -f {{ dc_file }} up -d"
  args:
    chdir: /tmp/